#include "StorageService.h"
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QStandardPaths>
#include <QUuid>
namespace { int i(const QJsonObject&o,const char*k,int d){auto v=o.value(k);return v.isDouble()?v.toInt(d):d;} double n(const QJsonObject&o,const char*k,double d){auto v=o.value(k);return v.isDouble()?v.toDouble(d):d;} bool b(const QJsonObject&o,const char*k,bool d){auto v=o.value(k);return v.isBool()?v.toBool():d;}
QJsonObject sj(const AppSettings&s){return {{"petScale",s.petScale},{"movementSpeed",s.movementSpeed},{"animationSpeed",s.animationSpeed},{"volume",s.volume},{"alwaysOnTop",s.alwaysOnTop},{"clickThrough",s.clickThrough},{"autoActivity",s.autoActivity},{"proactiveBubbles",s.proactiveBubbles},{"autoStart",s.autoStart},{"focusMinutes",s.focusMinutes},{"breakMinutes",s.breakMinutes},{"waterReminder",s.waterReminder},{"waterIntervalMinutes",s.waterIntervalMinutes},{"restReminder",s.restReminder},{"restIntervalMinutes",s.restIntervalMinutes}};}
AppSettings ps(const QJsonObject&o){AppSettings s;s.petScale=n(o,"petScale",s.petScale);s.movementSpeed=n(o,"movementSpeed",s.movementSpeed);s.animationSpeed=n(o,"animationSpeed",s.animationSpeed);s.volume=i(o,"volume",s.volume);s.alwaysOnTop=b(o,"alwaysOnTop",s.alwaysOnTop);s.clickThrough=b(o,"clickThrough",s.clickThrough);s.autoActivity=b(o,"autoActivity",s.autoActivity);s.proactiveBubbles=b(o,"proactiveBubbles",s.proactiveBubbles);s.autoStart=b(o,"autoStart",s.autoStart);s.focusMinutes=i(o,"focusMinutes",s.focusMinutes);s.breakMinutes=i(o,"breakMinutes",s.breakMinutes);s.waterReminder=b(o,"waterReminder",s.waterReminder);s.waterIntervalMinutes=i(o,"waterIntervalMinutes",s.waterIntervalMinutes);s.restReminder=b(o,"restReminder",s.restReminder);s.restIntervalMinutes=i(o,"restIntervalMinutes",s.restIntervalMinutes);s.sanitize();return s;}}
StorageService::StorageService(QString path):m_overridePath(std::move(path)){} QString StorageService::dataPath()const{if(!m_overridePath.isEmpty())return m_overridePath;auto d=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);QDir().mkpath(d);return d+"/study-pet.json";}
UserData StorageService::load()const{UserData d;QFile f(dataPath());if(!f.open(QIODevice::ReadOnly))return d;QJsonParseError e;auto doc=QJsonDocument::fromJson(f.readAll(),&e);if(e.error!=QJsonParseError::NoError||!doc.isObject())return d;auto r=doc.object();if(i(r,"schemaVersion",0)!=1)return d;d.settings=ps(r.value("settings").toObject());auto p=r.value("stats").toObject();d.stats.intimacy=i(p,"intimacy",0);d.stats.mood=i(p,"mood",60);d.stats.energy=i(p,"energy",100);d.stats.companionDays=i(p,"companionDays",1);d.stats.lastUsedDate=QDate::fromString(p.value("lastUsedDate").toString(),Qt::ISODate);d.stats.lastClickReward=QDateTime::fromString(p.value("lastClickReward").toString(),Qt::ISODate);d.stats.clamp();for(auto v:r.value("history").toArray()){auto o=v.toObject();auto day=QDate::fromString(o.value("date").toString(),Qt::ISODate);if(day.isValid())d.history.append({day,qMax(0,i(o,"focusMinutes",0)),qMax(0,i(o,"pomodoros",0))});}for(auto v:r.value("todos").toArray()){auto o=v.toObject();TodoItem t{o.value("id").toString(),o.value("title").toString(),b(o,"completed",false),QDateTime::fromString(o.value("createdAt").toString(),Qt::ISODate),QDate::fromString(o.value("dueDate").toString(),Qt::ISODate)};if(!t.id.isEmpty()&&!t.title.trimmed().isEmpty())d.todos.append(t);}return d;}
bool StorageService::save(const UserData&d)const{QJsonArray h,t;for(auto r:d.history)h.append(QJsonObject{{"date",r.date.toString(Qt::ISODate)},{"focusMinutes",r.focusMinutes},{"pomodoros",r.pomodoros}});for(auto x:d.todos)t.append(QJsonObject{{"id",x.id},{"title",x.title},{"completed",x.completed},{"createdAt",x.createdAt.toString(Qt::ISODate)},{"dueDate",x.dueDate.toString(Qt::ISODate)}});QJsonObject p{{"intimacy",d.stats.intimacy},{"mood",d.stats.mood},{"energy",d.stats.energy},{"companionDays",d.stats.companionDays},{"lastUsedDate",d.stats.lastUsedDate.toString(Qt::ISODate)},{"lastClickReward",d.stats.lastClickReward.toString(Qt::ISODate)}};QSaveFile f(dataPath());if(!f.open(QIODevice::WriteOnly))return false;f.write(QJsonDocument(QJsonObject{{"schemaVersion",1},{"settings",sj(d.settings)},{"stats",p},{"history",h},{"todos",t}}).toJson());return f.commit();}
void StorageService::addFocus(UserData&d,const QDate&day,int min){for(auto&r:d.history)if(r.date==day){r.focusMinutes+=min;++r.pomodoros;return;}d.history.append({day,min,1});}int StorageService::focusMinutes(const UserData&d,const QDate&day){for(auto&r:d.history)if(r.date==day)return r.focusMinutes;return 0;}int StorageService::pomodoroCount(const UserData&d,const QDate&day){for(auto&r:d.history)if(r.date==day)return r.pomodoros;return 0;}int StorageService::learningStreak(const UserData&d,const QDate&today){int r=0;for(auto day=today;focusMinutes(d,day)>0;day=day.addDays(-1))++r;return r;}void StorageService::upsertTodo(UserData&d,TodoItem x){if(x.title.trimmed().isEmpty())return;if(x.id.isEmpty())x.id=QUuid::createUuid().toString(QUuid::WithoutBraces);if(!x.createdAt.isValid())x.createdAt=QDateTime::currentDateTimeUtc();for(auto&t:d.todos)if(t.id==x.id){t=x;return;}d.todos.append(x);}void StorageService::removeTodo(UserData&d,const QString&id){for(int j=0;j<d.todos.size();++j)if(d.todos[j].id==id){d.todos.removeAt(j);return;}}

