#include "StorageService.h"
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QStandardPaths>
namespace { int number(const QJsonObject&o,const char*k,int d){return o.value(k).isDouble()?o.value(k).toInt(d):d;} }
QString StorageService::dataPath() const { const auto dir=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation); QDir().mkpath(dir); return dir+QStringLiteral("/study-pet.json"); }
UserData StorageService::load() const { UserData data; QFile f(dataPath()); if(!f.open(QIODevice::ReadOnly)) return data; QJsonParseError e; auto doc=QJsonDocument::fromJson(f.readAll(),&e); if(e.error!=QJsonParseError::NoError||!doc.isObject()) return data; auto r=doc.object(); if(number(r,"schemaVersion",0)!=1) return data; auto s=r.value("settings").toObject(); data.settings.petScale=s.value("petScale").toDouble(1); data.settings.movementSpeed=s.value("movementSpeed").toDouble(1); data.settings.focusMinutes=number(s,"focusMinutes",25); data.settings.breakMinutes=number(s,"breakMinutes",5); data.settings.sanitize(); auto p=r.value("stats").toObject(); data.stats.intimacy=number(p,"intimacy",0);data.stats.mood=number(p,"mood",60);data.stats.energy=number(p,"energy",100);data.stats.companionDays=number(p,"companionDays",1);data.stats.lastUsedDate=QDate::fromString(p.value("lastUsedDate").toString(),Qt::ISODate);data.stats.clamp(); for(auto v:r.value("history").toArray()){auto o=v.toObject();data.history.append({QDate::fromString(o.value("date").toString(),Qt::ISODate),number(o,"focusMinutes",0),number(o,"pomodoros",0)});} for(auto v:r.value("todos").toArray()){auto o=v.toObject();TodoItem t{o.value("id").toString(),o.value("title").toString(),o.value("completed").toBool(),QDateTime::fromString(o.value("createdAt").toString(),Qt::ISODate),QDate::fromString(o.value("dueDate").toString(),Qt::ISODate)};if(!t.id.isEmpty()&&!t.title.isEmpty())data.todos.append(t);} return data; }
bool StorageService::save(const UserData&d) const { QJsonObject s{{"petScale",d.settings.petScale},{"movementSpeed",d.settings.movementSpeed},{"focusMinutes",d.settings.focusMinutes},{"breakMinutes",d.settings.breakMinutes}}; QJsonObject p{{"intimacy",d.stats.intimacy},{"mood",d.stats.mood},{"energy",d.stats.energy},{"companionDays",d.stats.companionDays},{"lastUsedDate",d.stats.lastUsedDate.toString(Qt::ISODate)}};QJsonArray h,t;for(auto x:d.history)h.append(QJsonObject{{"date",x.date.toString(Qt::ISODate)},{"focusMinutes",x.focusMinutes},{"pomodoros",x.pomodoros}});for(auto x:d.todos)t.append(QJsonObject{{"id",x.id},{"title",x.title},{"completed",x.completed},{"createdAt",x.createdAt.toString(Qt::ISODate)},{"dueDate",x.dueDate.toString(Qt::ISODate)}});QSaveFile f(dataPath());if(!f.open(QIODevice::WriteOnly))return false;f.write(QJsonDocument(QJsonObject{{"schemaVersion",1},{"settings",s},{"stats",p},{"history",h},{"todos",t}}).toJson());return f.commit(); }
void StorageService::addFocus(UserData&d,const QDate&date,int minutes){for(auto &r:d.history)if(r.date==date){r.focusMinutes+=minutes;++r.pomodoros;return;}d.history.append({date,minutes,1});}

