#include "StorageService.h"

#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QStandardPaths>
#include <QUuid>

namespace {
int integer(const QJsonObject &object, const char *key, int fallback) { const auto value = object.value(key); return value.isDouble() ? value.toInt(fallback) : fallback; }
double number(const QJsonObject &object, const char *key, double fallback) { const auto value = object.value(key); return value.isDouble() ? value.toDouble(fallback) : fallback; }
bool boolean(const QJsonObject &object, const char *key, bool fallback) { const auto value = object.value(key); return value.isBool() ? value.toBool() : fallback; }
QJsonObject settingsToJson(const AppSettings &s) { return {{"petScale",s.petScale},{"movementSpeed",s.movementSpeed},{"animationSpeed",s.animationSpeed},{"volume",s.volume},{"alwaysOnTop",s.alwaysOnTop},{"clickThrough",s.clickThrough},{"autoActivity",s.autoActivity},{"proactiveBubbles",s.proactiveBubbles},{"autoStart",s.autoStart},{"focusMinutes",s.focusMinutes},{"breakMinutes",s.breakMinutes},{"waterReminder",s.waterReminder},{"waterIntervalMinutes",s.waterIntervalMinutes},{"restReminder",s.restReminder},{"restIntervalMinutes",s.restIntervalMinutes},{"aiBaseUrl",s.aiBaseUrl},{"aiModel",s.aiModel},{"aiTimeoutSeconds",s.aiTimeoutSeconds},{"aiContextLimit",s.aiContextLimit}}; }
AppSettings settingsFromJson(const QJsonObject&o) { AppSettings s; s.petScale=number(o,"petScale",s.petScale);s.movementSpeed=number(o,"movementSpeed",s.movementSpeed);s.animationSpeed=number(o,"animationSpeed",s.animationSpeed);s.volume=integer(o,"volume",s.volume);s.alwaysOnTop=boolean(o,"alwaysOnTop",s.alwaysOnTop);s.clickThrough=boolean(o,"clickThrough",s.clickThrough);s.autoActivity=boolean(o,"autoActivity",s.autoActivity);s.proactiveBubbles=boolean(o,"proactiveBubbles",s.proactiveBubbles);s.autoStart=boolean(o,"autoStart",s.autoStart);s.focusMinutes=integer(o,"focusMinutes",s.focusMinutes);s.breakMinutes=integer(o,"breakMinutes",s.breakMinutes);s.waterReminder=boolean(o,"waterReminder",s.waterReminder);s.waterIntervalMinutes=integer(o,"waterIntervalMinutes",s.waterIntervalMinutes);s.restReminder=boolean(o,"restReminder",s.restReminder);s.restIntervalMinutes=integer(o,"restIntervalMinutes",s.restIntervalMinutes);if(o.value("aiBaseUrl").isString())s.aiBaseUrl=o.value("aiBaseUrl").toString();if(o.value("aiModel").isString())s.aiModel=o.value("aiModel").toString();s.aiTimeoutSeconds=integer(o,"aiTimeoutSeconds",s.aiTimeoutSeconds);s.aiContextLimit=integer(o,"aiContextLimit",s.aiContextLimit);s.sanitize();return s; }
}

StorageService::StorageService(QString path):m_overridePath(std::move(path)) {}
QString StorageService::dataPath()const { if(!m_overridePath.isEmpty())return m_overridePath;const auto directory=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);QDir().mkpath(directory);return directory+QStringLiteral("/study-pet.json"); }
UserData StorageService::load()const { UserData data;QFile file(dataPath());if(!file.open(QIODevice::ReadOnly))return data;QJsonParseError error;const auto document=QJsonDocument::fromJson(file.readAll(),&error);if(error.error!=QJsonParseError::NoError||!document.isObject())return data;const auto root=document.object();const auto version=integer(root,"schemaVersion",0);if(version!=1&&version!=2)return data;data.settings=settingsFromJson(root.value("settings").toObject());const auto stats=root.value("stats").toObject();data.stats.intimacy=integer(stats,"intimacy",0);data.stats.mood=integer(stats,"mood",60);data.stats.energy=integer(stats,"energy",100);data.stats.companionDays=integer(stats,"companionDays",1);data.stats.lastUsedDate=QDate::fromString(stats.value("lastUsedDate").toString(),Qt::ISODate);data.stats.lastClickReward=QDateTime::fromString(stats.value("lastClickReward").toString(),Qt::ISODate);data.stats.clamp();for(const auto value:root.value("history").toArray()){const auto record=value.toObject();const auto date=QDate::fromString(record.value("date").toString(),Qt::ISODate);if(date.isValid())data.history.append({date,qMax(0,integer(record,"focusMinutes",0)),qMax(0,integer(record,"pomodoros",0))});}for(const auto value:root.value("todos").toArray()){const auto object=value.toObject();TodoItem item{object.value("id").toString(),object.value("title").toString(),boolean(object,"completed",false),QDateTime::fromString(object.value("createdAt").toString(),Qt::ISODate),QDate::fromString(object.value("dueDate").toString(),Qt::ISODate)};if(!item.id.isEmpty()&&!item.title.trimmed().isEmpty())data.todos.append(item);}for(const auto value:root.value("chatHistory").toArray()){const auto object=value.toObject();bool valid=false;const auto role=chatRoleFromName(object.value("role").toString(),&valid);const auto content=object.value("content").toString();if(valid&&!content.trimmed().isEmpty())data.chatHistory.append({role,content});}trimChatHistory(data);return data; }
bool StorageService::save(const UserData &source)const { UserData data=source;trimChatHistory(data);QJsonArray history,todos,chatHistory;for(const auto&r:data.history)history.append(QJsonObject{{"date",r.date.toString(Qt::ISODate)},{"focusMinutes",r.focusMinutes},{"pomodoros",r.pomodoros}});for(const auto&t:data.todos)todos.append(QJsonObject{{"id",t.id},{"title",t.title},{"completed",t.completed},{"createdAt",t.createdAt.toString(Qt::ISODate)},{"dueDate",t.dueDate.toString(Qt::ISODate)}});for(const auto&m:data.chatHistory)chatHistory.append(QJsonObject{{"role",chatRoleName(m.role)},{"content",m.content}});const QJsonObject stats{{"intimacy",data.stats.intimacy},{"mood",data.stats.mood},{"energy",data.stats.energy},{"companionDays",data.stats.companionDays},{"lastUsedDate",data.stats.lastUsedDate.toString(Qt::ISODate)},{"lastClickReward",data.stats.lastClickReward.toString(Qt::ISODate)}};QSaveFile file(dataPath());if(!file.open(QIODevice::WriteOnly))return false;const QJsonObject root{{"schemaVersion",2},{"settings",settingsToJson(data.settings)},{"stats",stats},{"history",history},{"todos",todos},{"chatHistory",chatHistory}};file.write(QJsonDocument(root).toJson());return file.commit(); }
void StorageService::addFocus(UserData&d,const QDate&date,int minutes){for(auto&r:d.history)if(r.date==date){r.focusMinutes+=minutes;++r.pomodoros;return;}d.history.append({date,minutes,1});}
int StorageService::focusMinutes(const UserData&d,const QDate&date){for(const auto&r:d.history)if(r.date==date)return r.focusMinutes;return 0;}
int StorageService::pomodoroCount(const UserData&d,const QDate&date){for(const auto&r:d.history)if(r.date==date)return r.pomodoros;return 0;}
int StorageService::learningStreak(const UserData&d,const QDate&today){int result=0;for(auto date=today;focusMinutes(d,date)>0;date=date.addDays(-1))++result;return result;}
void StorageService::upsertTodo(UserData&d,TodoItem item){if(item.title.trimmed().isEmpty())return;if(item.id.isEmpty())item.id=QUuid::createUuid().toString(QUuid::WithoutBraces);if(!item.createdAt.isValid())item.createdAt=QDateTime::currentDateTimeUtc();for(auto&existing:d.todos)if(existing.id==item.id){existing=item;return;}d.todos.append(item);}
void StorageService::removeTodo(UserData&d,const QString&id){for(int index=0;index<d.todos.size();++index)if(d.todos[index].id==id){d.todos.removeAt(index);return;}}
void StorageService::trimChatHistory(UserData&d){while(d.chatHistory.size()>qBound(2,d.settings.aiContextLimit,100))d.chatHistory.removeFirst();}

