#include "SettingsWindow.h"
#include <QCheckBox>
#include <QDialogButtonBox>
#include <QDoubleSpinBox>
#include <QFormLayout>
#include <QSpinBox>
SettingsWindow::SettingsWindow(QWidget*p):QDialog(p){setWindowTitle(QStringLiteral("StudyPet 设置"));auto*f=new QFormLayout(this);auto ds=[&](double a,double b,double v){auto*x=new QDoubleSpinBox(this);x->setRange(a,b);x->setSingleStep(.1);x->setValue(v);return x;};auto is=[&](int a,int b,int v){auto*x=new QSpinBox(this);x->setRange(a,b);x->setValue(v);return x;};m_scale=ds(.5,2,1);m_move=ds(.25,4,1);m_animation=ds(.25,4,1);m_volume=is(0,100,70);m_focus=is(1,180,25);m_break=is(1,60,5);m_waterInterval=is(5,360,45);m_restInterval=is(10,360,60);m_top=new QCheckBox(this);m_click=new QCheckBox(this);m_auto=new QCheckBox(this);m_bubble=new QCheckBox(this);m_startup=new QCheckBox(this);m_water=new QCheckBox(this);m_rest=new QCheckBox(this);m_top->setChecked(true);m_auto->setChecked(true);m_bubble->setChecked(true);m_water->setChecked(true);m_rest->setChecked(true);f->addRow("缩放",m_scale);f->addRow("移动速度",m_move);f->addRow("动画速度",m_animation);f->addRow("音量",m_volume);f->addRow("始终置顶",m_top);f->addRow("点击穿透",m_click);f->addRow("自动活动",m_auto);f->addRow("主动气泡",m_bubble);f->addRow("开机启动",m_startup);f->addRow("专注分钟",m_focus);f->addRow("休息分钟",m_break);f->addRow("喝水提醒",m_water);f->addRow("喝水间隔",m_waterInterval);f->addRow("久坐提醒",m_rest);f->addRow("久坐间隔",m_restInterval);auto*b=new QDialogButtonBox(QDialogButtonBox::Save|QDialogButtonBox::Cancel,this);f->addRow(b);connect(b,&QDialogButtonBox::accepted,this,[this]{auto s=collect();emit settingsApplied(s);accept();});connect(b,&QDialogButtonBox::rejected,this,&QDialog::reject);}
void SettingsWindow::setSettings(const AppSettings&s){m_scale->setValue(s.petScale);m_move->setValue(s.movementSpeed);m_animation->setValue(s.animationSpeed);m_volume->setValue(s.volume);m_top->setChecked(s.alwaysOnTop);m_click->setChecked(s.clickThrough);m_auto->setChecked(s.autoActivity);m_bubble->setChecked(s.proactiveBubbles);m_startup->setChecked(s.autoStart);m_focus->setValue(s.focusMinutes);m_break->setValue(s.breakMinutes);m_water->setChecked(s.waterReminder);m_waterInterval->setValue(s.waterIntervalMinutes);m_rest->setChecked(s.restReminder);m_restInterval->setValue(s.restIntervalMinutes);}
AppSettings SettingsWindow::collect()const{AppSettings s;s.petScale=m_scale->value();s.movementSpeed=m_move->value();s.animationSpeed=m_animation->value();s.volume=m_volume->value();s.alwaysOnTop=m_top->isChecked();s.clickThrough=m_click->isChecked();s.autoActivity=m_auto->isChecked();s.proactiveBubbles=m_bubble->isChecked();s.autoStart=m_startup->isChecked();s.focusMinutes=m_focus->value();s.breakMinutes=m_break->value();s.waterReminder=m_water->isChecked();s.waterIntervalMinutes=m_waterInterval->value();s.restReminder=m_rest->isChecked();s.restIntervalMinutes=m_restInterval->value();s.sanitize();return s;}

