#include "StudyWindow.h"
#include <QCheckBox>
#include <QDateEdit>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QPushButton>
#include <QTabWidget>
#include <QVBoxLayout>
StudyWindow::StudyWindow(QWidget*p):QDialog(p){setWindowTitle("StudyPet 学习工具");resize(440,380);auto tabs=new QTabWidget(this);auto root=new QVBoxLayout(this);root->addWidget(tabs);auto pom=new QWidget;auto pl=new QVBoxLayout(pom);m_timer=new QLabel("25:00",pom);pl->addWidget(m_timer);for(auto x:{qMakePair("开始",&StudyWindow::startRequested),qMakePair("暂停",&StudyWindow::pauseRequested),qMakePair("继续",&StudyWindow::resumeRequested),qMakePair("重置",&StudyWindow::resetRequested)}){auto b=new QPushButton(x.first,pom);pl->addWidget(b);connect(b,&QPushButton::clicked,this,x.second);}tabs->addTab(pom,"番茄钟");auto todo=new QWidget;auto tl=new QVBoxLayout(todo);m_title=new QLineEdit(todo);m_title->setPlaceholderText("待办标题");m_hasDue=new QCheckBox("设置截止日期",todo);m_due=new QDateEdit(QDate::currentDate(),todo);m_due->setCalendarPopup(true);m_due->setEnabled(false);auto save=new QPushButton("新增或保存待办",todo);m_todos=new QListWidget(todo);auto del=new QPushButton("删除选中",todo);tl->addWidget(m_title);tl->addWidget(m_hasDue);tl->addWidget(m_due);tl->addWidget(save);tl->addWidget(m_todos);tl->addWidget(del);connect(m_hasDue,&QCheckBox::toggled,m_due,&QWidget::setEnabled);connect(save,&QPushButton::clicked,this,[this]{if(m_title->text().trimmed().isEmpty())return;TodoItem t;t.id=m_todos->currentItem()?m_todos->currentItem()->data(Qt::UserRole).toString():QString();t.title=m_title->text().trimmed();t.dueDate=m_hasDue->isChecked()?m_due->date():QDate();emit todoSaved(t);m_title->clear();m_hasDue->setChecked(false);m_todos->setCurrentItem(nullptr);});connect(del,&QPushButton::clicked,this,[this]{if(auto x=m_todos->currentItem())emit todoRemoved(x->data(Qt::UserRole).toString());});connect(m_todos,&QListWidget::itemChanged,this,[this](QListWidgetItem*x){emit todoToggled(x->data(Qt::UserRole).toString(),x->checkState()==Qt::Checked);});connect(m_todos,&QListWidget::itemSelectionChanged,this,&StudyWindow::loadSelectedTodo);tabs->addTab(todo,"待办事项");m_today=new QLabel;tabs->addTab(m_today,"今日统计");m_week=new QLabel;tabs->addTab(m_week,"最近7天");m_stats=new QLabel;tabs->addTab(m_stats,"桌宠养成");}
void StudyWindow::setTimerText(const QString&s){m_timer->setText(s);}void StudyWindow::loadSelectedTodo(){auto x=m_todos->currentItem();if(!x)return;m_title->setText(x->data(Qt::UserRole+1).toString());auto d=x->data(Qt::UserRole+2).toDate();m_hasDue->setChecked(d.isValid());if(d.isValid())m_due->setDate(d);}
void StudyWindow::setData(const UserData&d,const QDate&today){m_today->setText(QString("今日专注 %1 分钟｜番茄钟 %2 次").arg(StorageService::focusMinutes(d,today)).arg(StorageService::pomodoroCount(d,today)));QString week;for(int k=6;k>=0;--k){auto day=today.addDays(-k);week+=day.toString("MM-dd")+": "+QString::number(StorageService::focusMinutes(d,day))+" 分钟\n";}m_week->setText(week);m_stats->setText(QString("亲密度 %1\n心情 %2\n体力 %3\n连续陪伴 %4 天\n连续学习 %5 天").arg(d.stats.intimacy).arg(d.stats.mood).arg(d.stats.energy).arg(d.stats.companionDays).arg(StorageService::learningStreak(d,today)));m_todos->blockSignals(true);m_todos->clear();for(auto x:d.todos){auto label=x.title+"（创建："+x.createdAt.toString("MM-dd")+"）"+(x.dueDate.isValid()?" 截止："+x.dueDate.toString("MM-dd"):"");auto item=new QListWidgetItem(label,m_todos);item->setData(Qt::UserRole,x.id);item->setData(Qt::UserRole+1,x.title);item->setData(Qt::UserRole+2,x.dueDate);item->setFlags(item->flags()|Qt::ItemIsUserCheckable);item->setCheckState(x.completed?Qt::Checked:Qt::Unchecked);}m_todos->blockSignals(false);}

