#include "StudyWindow.h"
#include <QDate>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QPushButton>
#include <QTabWidget>
#include <QVBoxLayout>
StudyWindow::StudyWindow(QWidget*p):QDialog(p){setWindowTitle("StudyPet 学习工具");resize(420,360);auto*tabs=new QTabWidget(this);auto root=new QVBoxLayout(this);root->addWidget(tabs);auto pom=new QWidget;auto pl=new QVBoxLayout(pom);m_timer=new QLabel("25:00",pom);pl->addWidget(m_timer);for(auto pair: {qMakePair("开始",&StudyWindow::startRequested),qMakePair("暂停",&StudyWindow::pauseRequested),qMakePair("继续",&StudyWindow::resumeRequested),qMakePair("重置",&StudyWindow::resetRequested)}){auto*b=new QPushButton(pair.first,pom);pl->addWidget(b);connect(b,&QPushButton::clicked,this,pair.second);}tabs->addTab(pom,"番茄钟");auto todo=new QWidget;auto tl=new QVBoxLayout(todo);m_newTodo=new QLineEdit(todo);auto add=new QPushButton("新增待办",todo);m_todos=new QListWidget(todo);auto del=new QPushButton("删除选中",todo);tl->addWidget(m_newTodo);tl->addWidget(add);tl->addWidget(m_todos);tl->addWidget(del);connect(add,&QPushButton::clicked,this,[this]{if(!m_newTodo->text().trimmed().isEmpty()){emit todoAdded(m_newTodo->text().trimmed());m_newTodo->clear();}});connect(del,&QPushButton::clicked,this,[this]{auto*x=m_todos->currentItem();if(x)emit todoRemoved(x->data(Qt::UserRole).toString());});connect(m_todos,&QListWidget::itemChanged,this,[this](QListWidgetItem*x){emit todoToggled(x->data(Qt::UserRole).toString(),x->checkState()==Qt::Checked);});tabs->addTab(todo,"待办事项");m_today=new QLabel;tabs->addTab(m_today,"今日统计");m_week=new QLabel;tabs->addTab(m_week,"最近7天");m_stats=new QLabel;tabs->addTab(m_stats,"桌宠养成");}
void StudyWindow::setTimerText(const QString&s){m_timer->setText(s);}void StudyWindow::setData(const UserData&d,const QDate&today){m_today->setText(QString("今日专注 %1 分钟｜番茄钟 %2 次").arg(StorageService::focusMinutes(d,today)).arg(StorageService::pomodoroCount(d,today)));QString week;for(int k=6;k>=0;--k){auto day=today.addDays(-k);week+=day.toString("MM-dd")+": "+QString::number(StorageService::focusMinutes(d,day))+" 分钟\n";}m_week->setText(week);m_stats->setText(QString("亲密度 %1\n心情 %2\n体力 %3\n连续陪伴 %4 天\n连续学习 %5 天").arg(d.stats.intimacy).arg(d.stats.mood).arg(d.stats.energy).arg(d.stats.companionDays).arg(StorageService::learningStreak(d,today)));m_todos->blockSignals(true);m_todos->clear();for(auto x:d.todos){auto*i=new QListWidgetItem(x.title+"（创建："+x.createdAt.toString("MM-dd")+"）",m_todos);i->setData(Qt::UserRole,x.id);i->setFlags(i->flags()|Qt::ItemIsUserCheckable);i->setCheckState(x.completed?Qt::Checked:Qt::Unchecked);}m_todos->blockSignals(false);}

